## 1. Read csv files

In [1]:
import pandas as pd

departments = pd.read_csv("init/raw_data/departments.csv")
dept_emp = pd.read_csv("init/raw_data/dept_emp.csv")
dept_manager = pd.read_csv("init/raw_data/dept_manager.csv")
employees = pd.read_csv("init/raw_data/employees.csv")
salaries = pd.read_csv("init/raw_data/salaries.csv")
titles = pd.read_csv("init/raw_data/titles.csv")


## 2. Preview data

In [2]:
departments.head(5)

dept_no        dept_name
0    d001        Marketing
1    d002          Finance
2    d003  Human Resources
3    d004       Production
4    d005      Development

In [3]:
dept_emp.head(5)

emp_no dept_no
0   10001    d005
1   10002    d007
2   10003    d004
3   10004    d004
4   10005    d003

In [4]:
dept_manager.head(5)

dept_no  emp_no
0    d001  110022
1    d001  110039
2    d002  110085
3    d002  110114
4    d003  110183

In [5]:
employees.head(5)

emp_no emp_title_id  birth_date  first_name  last_name sex   hire_date
0  473302        s0001   7/25/1953    Hideyuki   Zallocco   M   4/28/1990
1  475053        e0002  11/18/1954       Byong  Delgrande   F    9/7/1991
2   57444        e0002   1/30/1958       Berry       Babb   F   3/21/1992
3  421786        s0001   9/28/1957       Xiong   Verhoeff   M  11/26/1987
4  282238        e0003  10/28/1952  Abdelkader    Baumann   F   1/18/1991

In [6]:
salaries.head(5)

emp_no  salary
0   10001   60117
1   10002   65828
2   10003   40006
3   10004   40054
4   10005   78228

In [7]:
titles.head(5)

title_id               title
0    s0001               Staff
1    s0002        Senior Staff
2    e0001  Assistant Engineer
3    e0002            Engineer
4    e0003     Senior Engineer

## 3. Check for missing values/ unique values/ data type

### 3.1. departments

In [8]:
departments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   dept_no    9 non-null      object
 1   dept_name  9 non-null      object
dtypes: object(2)
memory usage: 272.0+ bytes


In [9]:
departments.describe()

dept_no  dept_name
count        9          9
unique       9          9
top       d001  Marketing
freq         1          1


> Departments table:
> - stores the ID and Name of all departments
> - ID and name are unique
> - no missing values
> - types: string

### 3.2. dept_emp

In [10]:
dept_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 331603 entries, 0 to 331602
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype 
---  ------   --------------   ----- 
 0   emp_no   331603 non-null  int64 
 1   dept_no  331603 non-null  object
dtypes: int64(1), object(1)
memory usage: 5.1+ MB


In [11]:
dept_emp.describe(include = 'all')

emp_no dept_no
count   331603.000000  331603
unique            NaN       9
top               NaN    d005
freq              NaN   85707
mean    253332.605025     NaN
std     161831.919445     NaN
min      10001.000000     NaN
25%      85005.500000     NaN
50%     250001.000000     NaN
75%     424999.500000     NaN
max     499999.000000     NaN

In [12]:
dept_emp['emp_no'].nunique()

300024

In [13]:
dept_emp.duplicated().sum()

0

> dept_emp:
> - stores department ID for all employee ID
> - no missing values
> - no duplicated row, indicating that (emp_no, dept_no) uniquely identifies each row in the table -> can be used as composite key
> - number of unique emp_no < number of rows (300024 < 331603), indicating that one employee can belong to multiple departments
> - types: emp_no(integer), dept_no(string)

### 3.3. dept_manager

In [14]:
dept_manager.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   dept_no  24 non-null     object
 1   emp_no   24 non-null     int64 
dtypes: int64(1), object(1)
memory usage: 512.0+ bytes


In [15]:
dept_manager.describe(include='all')

dept_no         emp_no
count       24      24.000000
unique       9            NaN
top       d004            NaN
freq         4            NaN
mean       NaN  110780.833333
std        NaN     627.958713
min        NaN  110022.000000
25%        NaN  110284.250000
50%        NaN  110646.000000
75%        NaN  111199.750000
max        NaN  111939.000000

In [16]:
dept_manager['emp_no'].nunique()

24

In [17]:
dept_manager.duplicated().sum()

0

> dept_manager:
> - stores employee ID of managers of all departments
> - no missing values
> - no duplicated row, indicating that (dept_no, emp_no) uniquely identifies each row in the table -> can be used as composite key
> - number of unique emp_no = number of rows, indicating that one employee can only be manager of at most 1 department
> - numebr of unique dept_no <  number of rows, indicating that one department can have multiple managers
> - types: dept_no (string), emp_no (integer)

### 3.4. employees

In [18]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300024 entries, 0 to 300023
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype 
---  ------        --------------   ----- 
 0   emp_no        300024 non-null  int64 
 1   emp_title_id  300024 non-null  object
 2   birth_date    300024 non-null  object
 3   first_name    300024 non-null  object
 4   last_name     300024 non-null  object
 5   sex           300024 non-null  object
 6   hire_date     300024 non-null  object
dtypes: int64(1), object(6)
memory usage: 16.0+ MB


In [19]:
employees.describe(include = 'all')

emp_no emp_title_id birth_date first_name last_name     sex  \
count   300024.000000       300024     300024     300024    300024  300024   
unique            NaN            7       4750       1276      1638       2   
top               NaN        s0001   3/8/1952     Shahab      Baba       M   
freq              NaN       107384         95        295       226  179973   
mean    253321.763392          NaN        NaN        NaN       NaN     NaN   
std     161828.235540          NaN        NaN        NaN       NaN     NaN   
min      10001.000000          NaN        NaN        NaN       NaN     NaN   
25%      85006.750000          NaN        NaN        NaN       NaN     NaN   
50%     249987.500000          NaN        NaN        NaN       NaN     NaN   
75%     424993.250000          NaN        NaN        NaN       NaN     NaN   
max     499999.000000          NaN        NaN        NaN       NaN     NaN   

        hire_date  
count      300024  
unique       5434  
top     6/20/1985  
freq          132  
mean          NaN  
std           NaN  
min           NaN  
25%           NaN  
50%           NaN  
75%           NaN  
max           NaN

In [20]:
employees['emp_no'].nunique()

300024

> employees:
> - stores information of all employees
> - no missing values
> - number of unique emp_no = number of row, indicating that all emp_no are unique -> used as primary key
> - sex is defined by a single letter (M or F)
> - types: emp_no (integer), birth_date & hire_date (date), others (string)

### 3.5. salaries

In [21]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300024 entries, 0 to 300023
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   emp_no  300024 non-null  int64
 1   salary  300024 non-null  int64
dtypes: int64(2)
memory usage: 4.6 MB


In [22]:
salaries.describe()

emp_no         salary
count  300024.000000  300024.000000
mean   253321.763392   52970.732451
std    161828.235540   14301.478491
min     10001.000000   40000.000000
25%     85006.750000   40000.000000
50%    249987.500000   48681.000000
75%    424993.250000   61758.000000
max    499999.000000  129492.000000

In [23]:
salaries['emp_no'].nunique()

300024

> salaries:
> - stores salary of all employees
> - no missing values
> - number of unique emp_no = number of row, indicating that all emp_no are unique -> used as primary key
> - salary is always positive (min 40k)
> - types: emp_no (integer), salary (integer but can use decimal as well)

### 3.6. titles

In [24]:
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   title_id  7 non-null      object
 1   title     7 non-null      object
dtypes: object(2)
memory usage: 240.0+ bytes


In [25]:
titles.describe()

title_id  title
count         7      7
unique        7      7
top       s0001  Staff
freq          1      1

> titles:
> - stores titles and title id
> - no missing values
> - all values are unique -> title_id can be used as primary key
> - types: string

# 4. Key summary

Based on our initial investigation, we can create the ERD for this HR database with some key points:
- 'titles' and 'departments' are independent tables with their ID columns being primary keys and no foreign keys (created first)
- 'employees' has emp_id as primary keys, and title_id as foreign key that refers to 'titles' (created after 'titles')
- 'salaries' has emp_id as primary keys, but it can also be foreign key that refers to 'employees' (created after 'employees'). This is to ensure a strict one-to-one relationship, and to enforce that an employee needs to exist first before the employee can have data in the 'salaries' table.
- 'dept_emp' and 'dept_manager' both use composite key with emp_id being foreign key that refers to 'employees' and dept_id that refers to 'departments' (created after 'employees' and 'departments')

Other notes on defining table schema:
- data is clean and can be imported directly into the database
- only emp_id is integer, other IDs are of string type
- can enfore data check on some columns such as sex or salary